# -*- coding: utf-8 -*-
"""21AIA26-ML Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upsDboZtXs5j9NyQAvOsq6_bnNahvcZR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.tree import export_graphviz
import graphviz

df=pd.read_csv("/content/HW2.csv")

df.tail()

df.head()

df.describe()

df.nunique()

df['age'].unique()

df['age'].unique()

plt.boxplot(df.DateoFdeath)
plt.show()

x = df[['gender','isPopular','isMarried','isNoble',]]
y = df['isAlive']

x_c = ['gender','isPopular','isMarried','isNoble',]

plt.figure(figsize =(25,30))
plotnumber = 1

for col in x_c:
    if plotnumber <= 6:
        ax = plt.subplot(5, 5, plotnumber)
        sns.boxplot(x[col])
        plt.xlabel(col, fontsize = 15)

    plotnumber += 1
plt.tight_layout()
plt.show()

, x_test, y_train, y_test=trx_trainain_test_split(x,y,test_size = 0.25, random_state=0)

st_x = StandardScaler()  
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

clf = DecisionTreeClassifier(criterion='gini',random_state=0)
clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

confusion_matrix(y_test,y_pred)

accuracy_score(y_test,y_pred)

graphviz.Source(export_graphviz(clf,feature_names=x.columns,filled=True))